# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 688af2ddf2825d1ed74d4d43d49e92677658b7954f6cc79a589befef518455a77e4068fd3cd8349339199e94bf3c687f9bfd553e1d9eb652418250fff4d5219b

test:
  secret_key_base: 05d2c3a4e0a12ac2829a7f56f98337f491a87a3d8e4bfa69f0aae07f8723cadc6e50782c2fe16313ccd87956f3e1880b46d376424dbdb33d073bdd53579ad786

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
